# Generated by Django 5.2.8 on 2025-11-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0006_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
