# Generated by Django 5.2.8 on 2025-11-15 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0007_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
