# Generated by Django 5.2.8 on 2025-11-15 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0011_remove_cart_item_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholders_name', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(24)])),
                ('card_expire_date', models.DateField()),
                ('CVC', models.IntegerField(max_length=3, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0), django.core.validators.MinLengthValidator(3)])),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yes.profile')),
            ],
        ),
    ]
