# Generated by Django 5.2.8 on 2025-11-15 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0012_paymentsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsystem',
            name='CVC',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
