# Generated by Django 5.2.8 on 2025-11-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0013_alter_paymentsystem_cvc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsystem',
            name='profile',
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yes.user'),
        ),
    ]
