# Generated by Django 5.2.8 on 2025-11-15 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0014_remove_paymentsystem_profile_paymentsystem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsystem',
            name='card_number',
            field=models.CharField(max_length=21, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
