# Generated by Django 5.2.8 on 2025-11-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0015_alter_paymentsystem_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='added', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='yes.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_additions', to='yes.user')),
            ],
            options={
                'verbose_name': 'Product History',
                'verbose_name_plural': 'Product Histories',
                'ordering': ['-added_at'],
            },
        ),
    ]
