# Generated by Django 5.2.8 on 2025-11-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes', '0016_producthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('1', '⭐ (1 Star)'), ('2', '⭐⭐ (2 Stars)'), ('3', '⭐⭐⭐ (3 Stars)'), ('4', '⭐⭐⭐⭐ (4 Stars)'), ('5', '⭐⭐⭐⭐⭐ (5 Stars)')], default='5', max_length=1)),
                ('comment', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateitem', to='yes.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yes.user')),
            ],
        ),
    ]
